#!/bin/bash
sudo apt-get update
sudo apt-get -y install apache2
sudo apt-get -y install php7.2
sudo apt-get install php7.2-mysql php7.2-cli php7.2-curl php7.2-mbstring php7.2-zip php7.2-xml -y
sudo apt-get install mysql-server -y
